import type { Campaign } from '../types';

const now = new Date('2026-02-24T10:00:00.000Z');

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    Id: 'campaign-1',
    OrganizationId: 'org-1',
    MenuId: 'menu-1',
    Name: 'Summer Sale 2026',
    Description: 'Special summer discounts on selected items and refreshing beverages',
    LimitedDuration: true,
    StartDate: now,
    EndDate: new Date('2026-08-30T10:00:00.000Z'),
    Enabled: true,
    Created: now,
  },
  {
    Id: 'campaign-2',
    OrganizationId: 'org-1',
    MenuId: 'menu-2',
    Name: 'Happy Hour Special',
    Description: 'Discounted drinks and appetizers during happy hour times',
    LimitedDuration: true,
    StartDate: now,
    EndDate: new Date('2026-05-30T10:00:00.000Z'),
    Enabled: true,
    Created: now,
  },
  {
    Id: 'campaign-3',
    OrganizationId: 'org-1',
    MenuId: 'menu-3',
    Name: 'Weekend Brunch Deal',
    Description: 'Special brunch menu with exclusive pricing every Saturday and Sunday',
    LimitedDuration: false,
    Enabled: false,
    Created: now,
  },
  {
    Id: 'campaign-4',
    OrganizationId: 'org-1',
    MenuId: 'menu-3',
    Name: "Valentine's Day Menu",
    Description: 'Romantic dinner packages and special desserts for couples',
    LimitedDuration: true,
    StartDate: now,
    EndDate: new Date('2026-02-14T20:00:00.000Z'),
    Enabled: false,
    Created: now,
  },
  {
    Id: 'campaign-5',
    OrganizationId: 'org-1',
    MenuId: 'menu-4',
    Name: 'Student Discount',
    Description: '15% off for students with valid student ID on weekdays',
    LimitedDuration: false,
    Enabled: true,
    Created: now,
  },
];
