import type { Product } from '../types';
import { Dietary } from '../types/enums';

// Extended Product type with category for menu display
export interface ProductWithCategory extends Product {
  Category: number;
}

// Mock product data - this will be replaced with real API data later
export const MOCK_PRODUCTS: ProductWithCategory[] = [
  // Pizzas (Category 0)
  {
    Id: '1',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Margherita Pizza","fi":"Margherita Pizza","sv":"Margherita Pizza"}',
    Description: '{"en":"Classic pizza with tomato sauce, mozzarella, and fresh basil","fi":"Klassinen pizza tomaattikastikkeella, mozzarellalla ja tuoreella basilikalla","sv":"Klassisk pizza med tomatsås, mozzarella och färsk basilika"}',
    Price: 12.99,
    Ingredients: '{"en":"flour, tomato sauce, mozzarella cheese, fresh basil, olive oil, salt","fi":"jauho, tomaattikastike, mozzarellajuusto, tuore basilika, oliiviöljy, suola","sv":"mjöl, tomatsås, mozzarellaost, färsk basilika, olivolja, salt"}',
    Dietaries: [Dietary.Vegetarian, Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
    Toppings: '[{"Name":{"en":"Extra Cheese","fi":"Lisäjuusto","sv":"Extra Ost"},"PriceIncrement":1.50},{"Name":{"en":"Mushrooms","fi":"Sienet","sv":"Svamp"},"PriceIncrement":1.00},{"Name":{"en":"Olives","fi":"Oliivit","sv":"Oliver"},"PriceIncrement":0.75}]',
  },
  {
    Id: '2',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Pepperoni Pizza"}',
    Description: '{"en":"Pizza topped with spicy pepperoni and mozzarella cheese"}',
    Price: 14.99,
    Ingredients: '{"en":"flour, tomato sauce, mozzarella cheese, pepperoni, olive oil, salt, pepper"}',
    Dietaries: [Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
    Toppings: '[{"Name":{"en":"Extra Pepperoni","fi":"Lisä Pepperoni","sv":"Extra Pepperoni"},"PriceIncrement":2.00},{"Name":{"en":"Jalapeños","fi":"Jalapeñot","sv":"Jalapeños"},"PriceIncrement":0.50},{"Name":{"en":"Extra Cheese","fi":"Lisäjuusto","sv":"Extra Ost"},"PriceIncrement":1.50}]',
  },
  {
    Id: '3',
    OrganizationId: 'mock-org-1',
    Name: '{"fi":"Havaiji Pizza"}',
    Description: '{"fi":"Pizza kinkkua, ananasta ja mozzarellaa"}',
    Price: 13.99,
    Ingredients: '{"fi":"jauho, tomaattikastike, mozzarellajuusto, kinkku, ananas, oliiviöljy, suola"}',
    Dietaries: [Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
    Toppings: '[{"Name":{"en":"Extra Ham","fi":"Lisäkinkku","sv":"Extra Skinka"},"PriceIncrement":2.00},{"Name":{"en":"Extra Pineapple","fi":"Lisäananas","sv":"Extra Ananas"},"PriceIncrement":1.00},{"Name":{"en":"Bacon","fi":"Pekoni","sv":"Bacon"},"PriceIncrement":1.50}]',
  },
  {
    Id: '4',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Veggie Supreme","fi":"Kasvis Supreme","sv":"Veggie Supreme"}',
    Description: '{"en":"Loaded with fresh vegetables and mozzarella","fi":"Täynnä tuoreita vihanneksia ja mozzarellaa","sv":"Fylld med färska grönsaker och mozzarella"}',
    Price: 13.49,
    Ingredients: '{"en":"flour, tomato sauce, mozzarella cheese, bell peppers, mushrooms, onions, olives, tomatoes, olive oil, salt","fi":"jauho, tomaattikastike, mozzarellajuusto, paprika, sienet, sipuli, oliivit, tomaatit, oliiviöljy, suola","sv":"mjöl, tomatsås, mozzarellaost, paprika, svamp, lök, oliver, tomater, olivolja, salt"}',
    Dietaries: [Dietary.Vegetarian, Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
    Toppings: '[{"Name":{"en":"Extra Veggies","fi":"Lisävihannekset","sv":"Extra Grönsaker"},"PriceIncrement":1.50},{"Name":{"en":"Vegan Cheese","fi":"Vegaanijuusto","sv":"Vegansk Ost"},"PriceIncrement":2.00},{"Name":{"en":"Garlic","fi":"Valkosipuli","sv":"Vitlök"},"PriceIncrement":0.50},{"Name":{"en":"Sun-dried Tomatoes","fi":"Auringonkuivatut tomaatit","sv":"Soltorkade Tomater"},"PriceIncrement":1.25}]',
  },
  {
    Id: '5',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"BBQ Chicken Pizza","fi":"BBQ Kana Pizza","sv":"BBQ Kyckling Pizza"}',
    Description: '{"en":"BBQ sauce, grilled chicken, red onions, and cilantro","fi":"BBQ-kastike, grillattu kana, punainen sipuli ja korianteri","sv":"BBQ-sås, grillad kyckling, rödlök och koriander"}',
    Price: 15.99,
    Ingredients: '{"en":"flour, BBQ sauce, mozzarella cheese, grilled chicken, red onions, cilantro, olive oil, salt","fi":"jauho, BBQ-kastike, mozzarellajuusto, grillattu kana, punainen sipuli, korianteri, oliiviöljy, suola","sv":"mjöl, BBQ-sås, mozzarellaost, grillad kyckling, rödlök, koriander, olivolja, salt"}',
    Dietaries: [Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
    Toppings: '[{"Name":{"en":"Extra Chicken","fi":"Lisäkana","sv":"Extra Kyckling"},"PriceIncrement":2.50},{"Name":{"en":"Bacon","fi":"Pekoni","sv":"Bacon"},"PriceIncrement":1.50},{"Name":{"en":"Jalapeños","fi":"Jalapeñot","sv":"Jalapeños"},"PriceIncrement":0.75},{"Name":{"en":"Ranch Drizzle","fi":"Ranch-kastike","sv":"Ranch Sås"},"PriceIncrement":0.50}]',
  },
  {
    Id: '6',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Meat Lover\'s Pizza", "fi":"Äijävege Pizza", "sv":"Köttälskare Pizza"}',
    Description: '{"en":"Loaded with pepperoni, sausage, ham, and bacon","fi":"Täynnä pepperonia, makkaraa, kinkkua ja pekonia","sv":"Fylld med pepperoni, korv, skinka och bacon"}',
    Price: 16.99,
    Ingredients: '{"en":"flour, tomato sauce, mozzarella cheese, pepperoni, sausage, ham, bacon, olive oil, salt","fi":"jauho, tomaattikastike, mozzarellajuusto, pepperoni, makkara, kinkku, pekoni, oliiviöljy, suola","sv":"mjöl, tomatsås, mozzarellaost, pepperoni, korv, skinka, bacon, olivolja, salt"}',
    Dietaries: [Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
    Toppings: '[{"Name":{"en":"Extra Pepperoni","fi":"Lisä Pepperoni","sv":"Extra Pepperoni"},"PriceIncrement":2.00},{"Name":{"en":"Ground Beef","fi":"Jauheliha","sv":"Nötfärs"},"PriceIncrement":2.00},{"Name":{"en":"Italian Sausage","fi":"Italialainen makkara","sv":"Italiensk Korv"},"PriceIncrement":2.00}]',
  },
  // Burgers (Category 1)
  {
    Id: '7',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Classic Burger","fi":"Klassikkoburger","sv":"Klassisk burgare"}',
    Description: '{"en":"Beef patty with lettuce, tomato, onion, and pickles","fi":"Naudanliha pihvi salaatilla, tomaatilla, sipulilla ja suolakurkulla","sv":"Nötköttsburgare med sallad, tomat, lök och pickles"}',
    Price: 9.99,
    Ingredients: '{"en":"wheat flour, beef, lettuce, tomato, onion, pickles, sesame seeds, salt, pepper","fi":"vehnäjauho, naudanliha, salaatti, tomaatti, sipuli, suolakurkku, seesaminsiemenet, suola, pippuri","sv":"vetemjöl, nötkött, sallad, tomat, lök, pickles, sesamfrön, salt, peppar"}',
    Dietaries: [Dietary.LactoseFree],
    ImgUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 1,
    Toppings: '[{"Name":{"en":"Bacon","fi":"Pekoni","sv":"Bacon"},"PriceIncrement":1.50},{"Name":{"en":"Extra Cheese","fi":"Lisäjuusto","sv":"Extra Ost"},"PriceIncrement":1.00},{"Name":{"en":"Fried Egg","fi":"Paistettu muna","sv":"Stekt Ägg"},"PriceIncrement":1.25},{"Name":{"en":"Avocado","fi":"Avokado","sv":"Avokado"},"PriceIncrement":2.00}]',
    Excludables: '[{"en":"Lettuce","fi":"Salaatti","sv":"Sallad"},{"en":"Tomato","fi":"Tomaatti","sv":"Tomat"},{"en":"Onion","fi":"Sipuli","sv":"Lök"},{"en":"Pickles","fi":"Suolakurkku","sv":"Pickles"}]',
  },
  {
    Id: '8',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Cheese Burger","fi":"Juustoburger","sv":"Ostburgare"}',
    Description: '{"en":"Double beef patty with melted cheese","fi":"Kaksois naudanliha pihvi sulatetulla juustolla","sv":"Dubbel nötköttsburgare med smält ost"}',
    Price: 10.99,
    Ingredients: '{"en":"wheat flour, beef, cheddar cheese, lettuce, tomato, onion, sesame seeds, salt, pepper, milk","fi":"vehnäjauho, naudanliha, cheddarjuusto, salaatti, tomaatti, sipuli, seesaminsiemenet, suola, pippuri, maito","sv":"vetemjöl, nötkött, cheddarost, sallad, tomat, lök, sesamfrön, salt, peppar, mjölk"}',
    Dietaries: [Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 1,
    Toppings: '[{"Name":{"en":"Extra Patty","fi":"Lisäpihvi","sv":"Extra Biff"},"PriceIncrement":3.00},{"Name":{"en":"Bacon","fi":"Pekoni","sv":"Bacon"},"PriceIncrement":1.50},{"Name":{"en":"Onion Rings","fi":"Sipulirenkaat","sv":"Lökringa"},"PriceIncrement":1.75}]',
    Excludables: '[{"en":"Cheese","fi":"Juusto","sv":"Ost"},{"en":"Lettuce","fi":"Salaatti","sv":"Sallad"},{"en":"Tomato","fi":"Tomaatti","sv":"Tomat"},{"en":"Onion","fi":"Sipuli","sv":"Lök"}]',
  },
  {
    Id: '9',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Bacon Burger"}',
    Description: '{"en":"Burger with crispy bacon and BBQ sauce"}',
    Price: 11.99,
    Ingredients: '{"en":"wheat flour, beef, bacon, cheddar cheese, lettuce, tomato, BBQ sauce, sesame seeds, salt, pepper, milk"}',
    Dietaries: [Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 1,
    Toppings: '[{"Name":{"en":"Extra Bacon","fi":"Lisäpekoni","sv":"Extra Bacon"},"PriceIncrement":2.00},{"Name":{"en":"Cheddar Cheese","fi":"Cheddarjuusto","sv":"Cheddarost"},"PriceIncrement":1.00},{"Name":{"en":"Caramelized Onions","fi":"Karamellisoitu sipuli","sv":"Karamelliserad Lök"},"PriceIncrement":1.25},{"Name":{"en":"Mushrooms","fi":"Sienet","sv":"Svamp"},"PriceIncrement":1.00}]',
    Excludables: '[{"en":"Bacon"},{"en":"Cheese"},{"en":"Lettuce"},{"en":"Tomato"},{"en":"BBQ Sauce"}]',
  },
  // Sides (Category 2)
  {
    Id: '10',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"French Fries","fi":"Ranskalaiset","sv":"Pommes Frites"}',
    Description: '{"en":"Crispy golden french fries","fi":"Rapeat kultaiset ranskalaiset","sv":"Krispiga gyllene pommes frites"}',
    Price: 4.99,
    Ingredients: '{"en":"potatoes, vegetable oil, salt","fi":"perunat, kasviöljy, suola","sv":"potatis, vegetabilisk olja, salt"}',
    Dietaries: [Dietary.GlutenFree, Dietary.LactoseFree, Dietary.Vegan],
    ImgUrl: 'https://images.unsplash.com/photo-1630384082554-e4e5c0e7b869?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 2,
    Toppings: '[{"Name":{"en":"Cheese Sauce","fi":"Juustokastike","sv":"Ostsås"},"PriceIncrement":1.50},{"Name":{"en":"Bacon Bits","fi":"Pekonipalat","sv":"Baconbitar"},"PriceIncrement":1.00},{"Name":{"en":"Truffle Oil","fi":"Tryffelijöljy","sv":"Tryffelolja"},"PriceIncrement":2.00},{"Name":{"en":"Chili Flakes","fi":"Chililhiutaleet","sv":"Chiliflingor"},"PriceIncrement":0.25}]',
  },
  {
    Id: '11',
    OrganizationId: 'mock-org-1',
    Name: '{"fi":"Sipulirenkaat"}',
    Description: '{"fi":"Rapeat panetoidut sipulirenkaat"}',
    Price: 5.49,
    Ingredients: '{"fi":"sipuli, vehnäjauho, panko, munat, maito, kasviöljy, suola"}',
    Dietaries: [Dietary.Vegetarian, Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1619221882783-4f9a5e2e3ee9?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 2,
  },
  {
    Id: '12',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Mozzarella Sticks","fi":"Mozzarella Tikut","sv":"Mozzarella Pinnar"}',
    Description: '{"en":"Breaded mozzarella sticks with marinara sauce","fi":"Panetoidut mozzarella tikut marinara kastikkeella","sv":"Panerade mozzarella pinnar med marinara sås"}',
    Price: 6.99,
    Ingredients: '{"en":"mozzarella cheese, wheat flour, breadcrumbs, eggs, milk, vegetable oil, salt","fi":"mozzarellajuusto, vehnäjauho, korppujauho, munat, maito, kasviöljy, suola","sv":"mozzarellaost, vetemjöl, ströbröd, ägg, mjölk, vegetabilisk olja, salt"}',
    Dietaries: [Dietary.Vegetarian],
    ImgUrl: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 2,
    Toppings: '[{"Name":{"en":"Ranch Dip","fi":"Ranch-dippi","sv":"Ranch Dip"},"PriceIncrement":0.50},{"Name":{"en":"Garlic Aioli","fi":"Valkosipuli-aioli","sv":"Vitlöksaioli"},"PriceIncrement":0.75},{"Name":{"en":"Spicy Mayo","fi":"Tulinen majoneesi","sv":"Kryddmajonnäs"},"PriceIncrement":0.50}]',
  },
  // Drinks (Category 3)
  {
    Id: '13',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Coca-Cola"}',
    Description: '{"en":"Classic Coca-Cola"}',
    Price: 2.99,
    Ingredients: '{"en":"carbonated water, sugar, caffeine, phosphoric acid, natural flavors"}',
    ImgUrl: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 3,
  },
  {
    Id: '14',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Sprite","fi":"Sprite","sv":"Sprite"}',
    Description: '{"en":"Refreshing lemon-lime soda","fi":"Virkistävä sitruuna-limejuoma","sv":"Förfriskande citron-lime läsk"}',
    Price: 2.99,
    Ingredients: '{"en":"carbonated water, sugar, citric acid, natural lemon-lime flavor","fi":"hiilihapotettu vesi, sokeri, sitruunahappo, luonnollinen sitrus-limu aromi","sv":"kolsyrat vatten, socker, citronsyra, naturlig citron-lime smak"}',
    ImgUrl: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 3,
  },
  {
    Id: '15',
    OrganizationId: 'mock-org-1',
    Name: '{"fi":"Appelsiinimehu"}',
    Description: '{"fi":"Tuorepuristettu appelsiinimehu"}',
    Price: 3.49,
    Ingredients: '{"fi":"appelsiini"}',
    ImgUrl: 'https://images.unsplash.com/photo-1560512823-829485b8bf24?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 3,
  },
  // Alcoholic Beverages
  {
    Id: '16',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Cabernet Sauvignon 6cl","fi":"Cabernet Sauvignon 6cl","sv":"Cabernet Sauvignon 6cl"}',
    Description: '{"en":"Red wine - Rich and full-bodied","fi":"Punaviini - Täyteläinen ja runsas","sv":"Rödvin - Fylligt och kraftfullt"}',
    Price: 5.50,
    Ingredients: '{"en":"red grapes, sulfites","fi":"punaviinirypäleet, sulfiitit","sv":"röda druvor, sulfiter"}',
    ImgUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: true,
    Category: 3,
  },
  {
    Id: '17',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Cabernet Sauvignon 12cl","fi":"Cabernet Sauvignon 12cl","sv":"Cabernet Sauvignon 12cl"}',
    Description: '{"en":"Red wine - Rich and full-bodied","fi":"Punaviini - Täyteläinen ja runsas","sv":"Rödvin - Fylligt och kraftfullt"}',
    Price: 9.50,
    Ingredients: '{"en":"red grapes, sulfites","fi":"punaviinirypäleet, sulfiitit","sv":"röda druvor, sulfiter"}',
    ImgUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: true,
    Category: 3,
  },
  {
    Id: '18',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Heineken","fi":"Heineken","sv":"Heineken"}',
    Description: '{"en":"Premium lager beer - 330ml","fi":"Premium lager olut - 330ml","sv":"Premium lageröl - 330ml"}',
    Price: 5.90,
    Ingredients: '{"en":"water, barley malt, hops, yeast","fi":"vesi, ohramallas, humala, hiiva","sv":"vatten, kornmalt, humle, jäst"}',
    ImgUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: true,
    Category: 3,
  },
  {
    Id: '19',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"San Miguel","fi":"San Miguel","sv":"San Miguel"}',
    Description: '{"en":"Spanish premium lager - 330ml","fi":"Espanjalainen premium lager - 330ml","sv":"Spansk premium lager - 330ml"}',
    Price: 5.90,
    Ingredients: '{"en":"water, barley malt, corn, hops, yeast","fi":"vesi, ohramallas, maissi, humala, hiiva","sv":"vatten, kornmalt, majs, humle, jäst"}',
    ImgUrl: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: true,
    Category: 3,
  },
];

// Base categories
export const MOCK_CATEGORIES = [
  '{"en":"Pizzas","fi":"Pizzat","sv":"Pizzor"}',
  '{"en":"Burgers","fi":"Hampurilaiset","sv":"Hamburgare"}',
  '{"en":"Sides","fi":"Lisukkeet","sv":"Tillbehör"}',
  '{"en":"Drinks","fi":"Juomat","sv":"Drycker"}',
];
